server:
  port: 8003

#mybatis配置
mybatis:
  type-aliases-package: com.youxin.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis.xml

#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
#    数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud-db-03?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234

    #springboot默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMills: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true


# eureka配置，表示服务需要注册到哪里
eureka:
  client:
    service-url:
#      单机：
#      defaultZone: http://localhost:7001/eureka/
#      集群：需要向每个集群中注册进去
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: sprincloud-eureka-provider-dept8003 # 修改eureka默认描述信息
    prefer-ip-address: true #自动获取本机url

#info配置,这里面的东西都是自己定义配置的
info:
  app.name: youxin-springcloud
  company.name: www.youxin.com
  auther: 廖友鑫